apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    run: wordpress
spec:
  ports:
  - port: 80
    name: wordpress
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
