apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistentvolume
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
